<template>
  <v-content>
    <home-hero></home-hero>
    <areas-section></areas-section>
    <about-section></about-section>
    <approach-section></approach-section>
    <services-section></services-section>
    <separator></separator>
    <contact-section></contact-section>
  </v-content>
</template>
